version: "3.8"

services:
  geth:
    image: ethereum/client-go
    pull_policy: always
    container_name: geth
    restart: unless-stopped
    ports:
      - 30303:30303
      - 30303:30303/udp
      - 8545:8545
      - 8546:8546
      - 8551:8551
    volumes:
      - ${GETH_DATADIR:-/data/geth}:/root/.ethereum
    stop_signal: SIGINT
    stop_grace_period: 2m
    healthcheck:
      test: [ "CMD-SHELL", "geth attach --exec eth.blockNumber" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - --http
      - --http.api=eth,net,web3
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      - --ws.origins=*
      - --ws.addr=0.0.0.0
      - --ws.api=eth,net,web3
      - --graphql
      - --graphql.corsdomain=*
      - --graphql.vhosts=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/root/.ethereum/jwt.hex
      - --authrpc.port=8551
      - --txlookuplimit=0
    logging:
      driver: json-file
      options:
        max-size: 2m
        max-file: 10
  prysm:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain
    pull_policy: always
    container_name: beacon
    restart: unless-stopped
    stop_grace_period: 2m
    volumes:
      - ${PRYSM_DATADIR:-/data/prysm}:/data
      - ${GETH_DATADIR:-/data/geth}:/geth
    depends_on:
      geth:
        condition: service_healthy
    command:
      - --accept-terms-of-use
      - --datadir=/data
      - --disable-monitoring
      - --rpc-host=0.0.0.0
      - --http-web3provider=http://geth:8545
      - --execution-endpoint=http://geth:8551
      - --jwt-secret=/geth/jwt.hex
      - --grpc-gateway-host=0.0.0.0
      - --grpc-gateway-corsdomain=*
    logging:
      driver: json-file
      options:
        max-size: 2m
        max-file: 10
