apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prysm
spec:
  selector:
    matchLabels:
      app: prysm
  serviceName: prysm
  template:
    metadata:
      labels:
        app: prysm
    spec:
      terminationGracePeriodSeconds: 300
      containers:
        - name: beacon
          image: gcr.io/prysmaticlabs/prysm/beacon-chain
          args:
            - "--accept-terms-of-use"
            - "--datadir=/data"
            - "--disable-monitoring"
            - "--rpc-host=0.0.0.0"
            - "--http-web3provider=http://geth.chainrpc.svc.cluster.local:8545"
            - "--execution-endpoint=http://geth.chainrpc.svc.cluster.local:8551"
            - "--jwt-secret=/gethjwt/jwt.hex"
            - "--grpc-gateway-host=0.0.0.0"
            - "--grpc-gateway-corsdomain=*"
          ports:
            - containerPort: 4000
            - containerPort: 3500
            - containerPort: 13000
            - containerPort: 12000
              protocol: UDP
          readinessProbe:
            tcpSocket:
              port: 4000
          livenessProbe:
            tcpSocket:
              port: 4000
          startupProbe:
            failureThreshold: 720
            periodSeconds: 10
            tcpSocket:
              port: 4000
          resources:
            limits:
              cpu: 16000m
              memory: 8G
            requests:
              cpu: 1000m
              memory: 4G
          volumeMounts:
            - mountPath: "/data"
              name: chaindata
            - mountPath: "/gethjwt"
              name: gethjwt
      volumes:
        - name: chaindata
          persistentVolumeClaim:
            claimName: chaindata-prysm
        - configMap:
            name: geth-jwt
          name: gethjwt
