apiVersion: v1
kind: Service
metadata:
  name: geth
  namespace: chainrpc
spec:
  ports:
    - protocol: TCP
      targetPort: 8545
      port: 8545
      name: http
    - protocol: TCP
      targetPort: 8546
      port: 8546
      name: websoket
    - protocol: TCP
      targetPort: 8551
      port: 8551
      name: authrpc
  clusterIP: None
  selector:
    app: geth
